### PR TITLE
Fix issue9

### LINKED ISSUE #9: false-positive: test function names
The `_` is valid inside a test name: it's a basic pattern for non-exposed functions, methods, etc.

```go
func Test_myFunction(t *testing.T) {

}
```

```go
func TestMyStruct_myMethod(t *testing.T) {

}
```

### PR DESCRIPTION
**Pull request by sivchari**
close #9

FYI
https://go.dev/blog/examples

### CODE REVIEW

File: nosnakecase.go [hunk 1]
```diff
@@ -50,6 +50,12 @@ func report(pass *analysis.Pass, pos token.Pos, name string) {
 		return
 	}
 
+	// If prefix is Test or Benchmark, Fuzz, skip
+	// FYI https://go.dev/blog/examples
+	if strings.Contains(name, "Test") || strings.Contains(name, "Benchmark") || strings.Contains(name, "Fuzz") {
```
Comment (ldez) [inline nosnakecase.go:55]: I think this is too open, you will have false-negative now: if an Ident contains the word `Test` you will skip the check.
You should be more specific.

Comment (ldez) [reply nosnakecase.go:55]: at least a `HasPrefix` instead of `Contains`

Comment (sivchari) [reply nosnakecase.go:55]: Oh, I've mistook. I'll fix it.
